<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE BOE [
    <!-- Aquí comienza el DTD -->
    <!ELEMENT BOE (TITULO, FECHA, SUMARIO)>
    <!ELEMENT TITULO (#PCDATA)>
    <!ELEMENT FECHA (AAAA, MM, DD)>
    <!ELEMENT AAAA (#PCDATA)>
    <!ELEMENT MM (#PCDATA)>
    <!ELEMENT DD (#PCDATA)>
    <!ELEMENT SUMARIO (SECCION+)>
    <!ELEMENT SECCION (TIT-SECCION, APARTADO+)>
    <!ELEMENT TIT-SECCION (#PCDATA)>
    <!ELEMENT APARTADO (ORGANISMO, PARRAFO+)>
    <!ELEMENT ORGANISMO (#PCDATA)>
    <!ELEMENT PARRAFO (TEXTO, PAGINA+)>
    <!ELEMENT TEXTO (LEY*,ORDEN*,RD*, RES*, CORRECCION*)>
    <!ELEMENT PAGINA (#PCDATA)>
    <!ELEMENT ORDEN (#PCDATA)>
    <!ELEMENT LEY (#PCDATA)>
    <!ELEMENT RD (#PCDATA)>
    <!ELEMENT RES (#PCDATA)>
    <!ELEMENT CORRECCION (#PCDATA)>
    <!-- Aquí termina el DTD -->
]>
<BOE>
    <TITULO>BOLETIN OFICIAL DEL ESTADO</TITULO>
    <FECHA>
        <AAAA>2001</AAAA>
        <MM>03</MM>
        <DD>27</DD>
    </FECHA>
    <SUMARIO>
        <SECCION>
            <TIT-SECCION>I. Disposiciones Generales</TIT-SECCION>
            <APARTADO>
                <ORGANISMO>MINISTERIO DE ASUNTOS EXTERIORES</ORGANISMO>
                <PARRAFO>
                    <TEXTO>
                        <LEY>Ley 1/2001 de 5 de marzo de la cesión gratuita a las Comunidades
                            Autónomas el Impuesto sobre Animales y Cosas establecido por el </LEY>
                        <RD>REAL DECRETO 13/1991</RD>
                    </TEXTO>
                    <PAGINA>11290</PAGINA>
                </PARRAFO>
                <PARRAFO>
                    <TEXTO>
                        <ORDEN>ORDEN de 28 de febrero de 2001 por la ... </ORDEN>
                    </TEXTO>
                    <PAGINA>11290</PAGINA>
                    <PAGINA>11291</PAGINA>
                </PARRAFO>
            </APARTADO>
            <APARTADO>
                <ORGANISMO>MINISTERIO DE HACIENDA</ORGANISMO>
                <PARRAFO>
                    <TEXTO>
                        <RD>REAL DECRETO 285/2001, de 19 de marzo, sobre ... </RD>
                    </TEXTO>
                    <PAGINA>11291</PAGINA>
                    <PAGINA>11292</PAGINA>
                    <PAGINA>11293</PAGINA>
                    <PAGINA>11294</PAGINA>
                </PARRAFO>
            </APARTADO>
            <APARTADO>
                <ORGANISMO>MINISTERIO DE FOMENTO</ORGANISMO>
                <PARRAFO>
                    <TEXTO>
                        <CORRECCION>CORRECCIÓN de erratas de la Orden ...</CORRECCION>
                    </TEXTO>
                    <PAGINA>11291</PAGINA>
                    <PAGINA>11292</PAGINA>
                    <PAGINA>11293</PAGINA>
                    <PAGINA>11294</PAGINA>
                </PARRAFO>
            </APARTADO>
        </SECCION>
        <SECCION>
            <TIT-SECCION>II. Autoridades y Personal</TIT-SECCION>
            <APARTADO>
                <ORGANISMO>CORTES GENERALES</ORGANISMO>
                <PARRAFO>
                    <TEXTO>
                        <RES>RESOLUCIÓN de 19 de marzo de 2001, de la ... </RES>
                    </TEXTO>
                    <PAGINA>11294</PAGINA>
                    <PAGINA>11295</PAGINA>
                </PARRAFO>
            </APARTADO>
            <APARTADO>
                <ORGANISMO>MINISTERIO DE ASUNTOS EXTERIORES</ORGANISMO>
                <PARRAFO>
                    <TEXTO>
                        <RD>REAL DECRETO 314/2001, de 24 de marzo, por el ... </RD>
                    </TEXTO>
                    <PAGINA>11291</PAGINA>
                    <PAGINA>11292</PAGINA>
                    <PAGINA>11293</PAGINA>
                    <PAGINA>11294</PAGINA>
                </PARRAFO>
            </APARTADO>
        </SECCION>
    </SUMARIO>
</BOE>